spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        username: root
        password: Ccjsj1200#@!
        url: jdbc:mysql://119.23.18.147:3396/was?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&failOverReadOnly=false
        driver-class-name: com.mysql.cj.jdbc.Driver
server:
    port: 3396


mybatis:
    mapper-locations: classpath:mapping/*Mapper.xml
    type-aliases-package: com.example.springbootswagger.entity

#showSql
logging:
    level:
        com:
            example:
                mapper : debug
